In [21]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
import csv

In [22]:
# Load dataset - https://www.kaggle.com/datasets/prasad22/healthcare-dataset
df = pd.read_csv("healthcare_dataset.csv")

In [23]:
# Remove personally identifiable information
df = df.drop(['Name'], axis=1)

In [24]:
# Numerical Data that should be normalized to a 0-1 range to improve compatibility with LLMs
scaler = MinMaxScaler()
columns = ['Age', 'Billing Amount']
for c in columns:
    df[[c]] = scaler.fit_transform(df[[c]])
df.head()

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,0.223684,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,0.380933,328,Urgent,2024-02-02,Paracetamol,Normal
1,0.644737,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,0.650904,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,0.828947,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,0.547053,205,Emergency,2022-10-07,Aspirin,Normal
3,0.197368,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,0.728798,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,0.394737,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,0.296622,458,Urgent,2022-10-09,Penicillin,Abnormal

In [25]:
# Categorical Data 
encoder = LabelEncoder()
columns = ['Gender', 'Blood Type', 'Medical Condition', 'Doctor', 'Hospital', 'Insurance Provider', 'Admission Type', 'Medication', 'Test Results']
for c in columns:
    df[c] = encoder.fit_transform(df[c])
    print(c, encoder.classes_, len(encoder.classes_))
df.head()

Gender ['Female' 'Male'] 2
Blood Type ['A+' 'A-' 'AB+' 'AB-' 'B+' 'B-' 'O+' 'O-'] 8
Medical Condition ['Arthritis' 'Asthma' 'Cancer' 'Diabetes' 'Hypertension' 'Obesity'] 6
Doctor ['Aaron Acevedo' 'Aaron Adams' 'Aaron Aguilar' ... 'Zoe Nichols'
 'Zoe Roberts' 'Zoe Wallace'] 40341
Hospital ['Abbott Inc' 'Abbott Ltd' 'Abbott Moore and Williams,' ...
 'and Zuniga Francis Peterson,' 'and Zuniga Sons'
 'and Zuniga Thompson, Blake'] 39876
Insurance Provider ['Aetna' 'Blue Cross' 'Cigna' 'Medicare' 'UnitedHealthcare'] 5
Admission Type ['Elective' 'Emergency' 'Urgent'] 3
Medication ['Aspirin' 'Ibuprofen' 'Lipitor' 'Paracetamol' 'Penicillin'] 5
Test Results ['Abnormal' 'Inconclusive' 'Normal'] 3

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,0.223684,1,5,2,2024-01-31,26612,29933,1,0.380933,328,2,2024-02-02,3,2
1,0.644737,1,0,5,2019-08-20,33648,16012,3,0.650904,265,1,2019-08-26,1,1
2,0.828947,0,1,5,2022-09-22,37828,5473,0,0.547053,205,1,2022-10-07,0,2
3,0.197368,0,6,3,2020-11-18,22511,12317,3,0.728798,450,0,2020-12-18,1,0
4,0.394737,0,2,2,2022-09-19,21259,33598,0,0.296622,458,2,2022-10-09,4,0

In [26]:
df.to_csv('healthcare_dataset_preprocessed.csv', index = False)